import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { RouterModule } from '@angular/router';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

interface SeizureLog {
  _id: string; // Updated to use MongoDB _id field
  id: string;
  date: Date;
  type: string;
  duration: string;
  triggers: string;
}

interface Patient {
  _id: string;
  name: string;
  age: number;
  gender: string;
  dateOfBirth: Date;
  seizureLogs: SeizureLog[];
}

@Component({
  selector: 'app-seizure-logs',
  standalone: true,
  imports: [CommonModule, HttpClientModule, RouterModule, ReactiveFormsModule],
  templateUrl: './seizure-logs.component.html',
  styleUrls: ['./seizure-logs.component.scss']
})
export class SeizureLogsComponent implements OnInit {
  patients: Patient[] = [];
  filteredPatients: Patient[] = [];
  selectedPatient: Patient | null = null;
  seizureLogForm: FormGroup;
  isEditing: boolean = false;
  editingLogId: string | null = null;

  constructor(private http: HttpClient, private fb: FormBuilder) { 
    this.seizureLogForm = this.fb.group({
      date: ['', Validators.required],
      type: ['', Validators.required],
      duration: ['', Validators.required],
      triggers: ['', Validators.required]
    });
  }

  ngOnInit(): void {
    this.fetchPatients();
  }

  fetchPatients(): void {
    this.http.get<Patient[]>('http://localhost:3000/api/seizure-logs').subscribe({
      next: (data: Patient[]) => {
        this.patients = data;
        this.filteredPatients = [];
      },
      error: (err) => {
        console.error('Error fetching patients:', err);
      }
    });
  }

  applyFilter(event: Event): void {
    const input = event.target as HTMLInputElement;
    const filterValue = input.value.toLowerCase().trim();
    if (filterValue) {
      this.filteredPatients = this.patients.filter(patient =>
        patient.name.toLowerCase().includes(filterValue)
      );
    } else {
      this.filteredPatients = [];
    }
  }

  selectPatient(patient: Patient): void {
    this.selectedPatient = patient;
    this.isEditing = false;
  }

  addSeizureLog(): void {
    this.isEditing = true;
    this.editingLogId = null;
    this.seizureLogForm.reset();
  }

  editSeizureLog(log: SeizureLog): void {
    this.isEditing = true;
    this.editingLogId = log.id;
    // Ensure log.date is a Date object before converting to ISO string
    const logDate = new Date(log.date);
    this.seizureLogForm.patchValue({
      date: logDate.toISOString().substring(0, 10), // Format date for input[type="date"]
      type: log.type,
      duration: log.duration,
      triggers: log.triggers
    });
  }
  

  saveSeizureLog(): void {
    if (this.selectedPatient && this.seizureLogForm.valid) {
      if (this.editingLogId === null) {
        // Adding new seizure log
        const newLog: SeizureLog = {
          _id: '', // Will be generated by MongoDB
          id: new Date().getTime().toString(), // Generate a new ID based on timestamp
          ...this.seizureLogForm.value,
          date: new Date(this.seizureLogForm.value.date)
        };
        this.http.post<Patient>(`http://localhost:3000/api/seizure-logs/${this.selectedPatient._id}`, newLog).subscribe({
          next: (updatedPatient) => {
            this.selectedPatient = updatedPatient;
            this.seizureLogForm.reset();
            this.isEditing = false;
          },
          error: (err) => {
            console.error('Error adding seizure log:', err);
          }
        });
      } else {
        // Editing existing seizure log
        const updatedLog = {
          ...this.seizureLogForm.value,
          date: new Date(this.seizureLogForm.value.date)
        };
        this.http.put<Patient>(`http://localhost:3000/api/seizure-logs/${this.selectedPatient._id}/${this.editingLogId}`, updatedLog).subscribe({
          next: (updatedPatient) => {
            this.selectedPatient = updatedPatient;
            this.isEditing = false;
            this.editingLogId = null;
            this.seizureLogForm.reset();
          },
          error: (err) => {
            console.error('Error saving seizure log:', err);
          }
        });
      }
    } else {
      console.error('Form is invalid or no patient selected.');
    }
  }

  cancelEdit(): void {
    this.isEditing = false;
    this.editingLogId = null;
    this.seizureLogForm.reset();
  }

  deleteSeizureLog(id: string): void {
    if (this.selectedPatient) {
      console.log(`Deleting log ID: ${id} for patient ID: ${this.selectedPatient._id}`);
      this.http.delete<Patient>(`http://localhost:3000/api/seizure-logs/${this.selectedPatient._id}/${id}`).subscribe({
        next: (updatedPatient) => {
          this.selectedPatient = updatedPatient;
        },
        error: (err) => {
          console.error('Error deleting seizure log:', err);
        }
      });
    }
  }
}
